services:
  db:
    image: postgres:15
    container_name: weather_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: weather_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  ingestion:
    build:
      context: ./ingestion
    env_file:
      - .env
    volumes:
      - ./ingestion:/app
    depends_on:
      - db
    profiles:
      - ingestion

  jupyter:
    build:
      context: ./notebooks
      dockerfile: Dockerfile
    container_name: weather-jupyter
    profiles:
      - notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db-data:
  pgadmin_data:


# TO RUN

# Jupyter Lab
# docker compose --profile notebook up --build jupyter